version: '3'

volumes:
  mysql_data:
    driver: local

networks:
  docker_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24

services:
  mysql:
    image: mysql:5.7
    environment:
      BIND_ADDRESS: 0.0.0.0
    networks:
      docker_network:
        aliases:
          - mysql
        ipv4_address: 172.10.0.101
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  php-cli:
    build: docker/cli
    networks:
      docker_network:
        aliases:
          - php-cli
        ipv4_address: 172.10.0.102
    working_dir: /var/www/
    volumes:
      - .:/var/www

  php-fpm:
    build: docker/fpm
    expose:
      - 9000
    networks:
      docker_network:
        aliases:
          - php-fpm
        ipv4_address: 172.10.0.103
    working_dir: /var/www/
    volumes:
      - .:/var/www

  apache:
    build: docker/apache
    working_dir: /var/www/
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PID_FILE: /var/run/apache2/apache2.pid
      APACHE_RUN_DIR: /var/run/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
      APACHE_LOG_DIR: /var/log/apache2
    ports:
      - 80:80
      - 443:443
    networks:
      docker_network:
        aliases:
          - apache
        ipv4_address: 172.10.0.104
    volumes:
      - .:/var/www
    tty: true

  # container usage:
  #  docker-compose run composer [command]
  composer:
    build: docker/composer
    working_dir: /var/www/
    networks:
      docker_network:
        aliases:
          - composer
        ipv4_address: 172.10.0.105
    volumes:
      - .:/var/www
    command: -q
