version: '3'

volumes:
  mysql_data:
    driver: local

networks:
  docker_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24

services:
  mysql:
    image: mysql:5.7
    environment:
      BIND_ADDRESS: 0.0.0.0
      MYSQL_ROOT_PASSWORD: pfm
      MYSQL_DATABASE: pfm
      MYSQL_USER: pfm
      MYSQL_PASSWORD: pfm
    networks:
      docker_network:
        aliases:
          - mysql
        ipv4_address: 172.10.0.101
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  php-fpm:
    build: docker/fpm
    expose:
      - 9000
    networks:
      docker_network:
        aliases:
          - php-fpm
        ipv4_address: 172.10.0.102
    working_dir: /var/www/
    volumes:
      - .:/var/www

  apache:
    build: docker/apache
    working_dir: /var/www/
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PID_FILE: /var/run/apache2/apache2.pid
      APACHE_RUN_DIR: /var/run/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
      APACHE_LOG_DIR: /var/log/apache2
      APP_DOMAIN: pfm-app
      APP_DOC_ROOT: /var/www/public
      APACHE_SERVERNAME: pfm-server
      FPM_ALIAS: fpm
    ports:
      - 80:80
      - 443:443
    networks:
      docker_network:
        aliases:
          - apache
        ipv4_address: 172.10.0.103
    volumes:
      - .:/var/www
    tty: true
